### ISSUE TITLE
Adjust to Video Position (Anchor Last/First Line)

### ISSUE THREAD

**Issue by gorn** [maxrd2/subtitlecomposer#11]
Maybe I am overlooking something terribly, but I found two commands very inuntiative, namely "Adjust to Video Position (Anchor Last/First Line)". Let me explain: 

The easiest way I found to adjust timing when subtitles are slowing down gradually during the film is to locate one line at the beginning of the film, fix it to the right place in video and then do the same with another line in the end. The program having these two lines fixed to film can recalrulate the rest easily. All the time I used subtitlecomposer I thought that these commands are (Alt-Z / Alt-X) doing exactly this, because it just worked. Now I looked at what their text in menu is saying and I was surprised that the wording is the other way round. I was about to fork the repo and correct it when I found that actually there are doing something very different - they are two independent commads and the fact it sort of works the way I was using it is just coincidence. 

I suggest that either the wording is changed and/or the feature is implemented as I tought it would work, because I think it is much more usefull than the way it is now. (Of course keep the current commands available as well). It is far more accurate when one uses two lines to as anchors, than when one uses one line and the end of the film (or the beginning). Very often there are some lines like credit at the end or at the beginning of subtitles which do not synchroniye to anything in the film.

Hopefully I have expressed myself clearly. Sorrz English is not my mothers tongue.

**Comment by maxrd2** [comment]
I know it's been long time since you reported this, but have finally added support for anchor points.
You can anchor one or more lines. Editing show time of one of these will "stretch" the timeline between selected and adjanced anchor points.

In order to adjust times like I think you wanted you should:
- anchor some line near the beginning of the video
- anchor some line near the end of the video
- edit show times of two anchored lines to match the position in audio/video
- rest of the lines will linearly stretch to appropriate positions

**Comment by gorn** [comment]
Thank you, I will try this.
