### ISSUE TITLE
Create and publish AppImage from current master.

### ISSUE THREAD

**Issue by maxrd2** [maxrd2/subtitlecomposer#114]
Make a script that will generate AppImage and make it available for download automatically each time stuff is pushed to master. Preferably do the builds using Travis CI.

**Comment by Martchus** [comment]
I have already done something similar for my own projects using OBS: https://build.opensuse.org/project/show/home:mkittler:appimage:vcs

You might consider that option, too. Pulling via Git (as opposed to simply downloading a release tarball) works as long as no sub-modules are used. The nice thing is that you only need to provide an `appimage.yml` and it does the rest for you. The bad thing is that you give up control.

**Comment by Martchus** [comment]
If you need to build dependencies yourself because the version in Leap is too outdated or the package is missing at all the OBS option is likely not so nice anymore. Last time I used it I've only got Qt 5.6.x which was almost too outdated. Not sure what I would have had to do to get a newer version for instance.
