### ISSUE TITLE
Waveform support

### ISSUE THREAD

**Issue by lunarrunner** [maxrd2/subtitlecomposer#26]
Having a waveform would make time adjustment a lot easier in my opinion. Is it possible to implement this feature into Subtitle Composer?

**Comment by maxrd2** [comment]
yes... was planning to add it for some time.
Hope it will be up and ready soon.

**Comment by maxrd2** [comment]
Have uploaded initial implementation of this.
Still planning to add:
- ability to drag subtitle borders in order to move/change/edit subtitle show/hide times
- zoom in/out buttons
- two scroll modes:
 - manual scroll / follow selected subtitle
 - follow video (like it's now)

Other/different ideas are welcome :)

**Comment by Martchus** [comment]
Just checked out your implementation and it works fine. Thanks for the work.
