### ISSUE TITLE
Xplayer support

### ISSUE THREAD

**Issue by muzena** [maxrd2/subtitlecomposer#50]
Can you add suport for xplayer, it is Linux Mint new fork of totem.
Totem will be replaced by xplayer in new Linux Mint 18 Sarah.
https://github.com/linuxmint/xplayer
https://github.com/linuxmint/xplayer-plparser

**Comment by maxrd2** [comment]
I don't see any api to integrate it into 3rd party apps mentioned anywhere.
Without it it would be pretty much impossible to integrate it.
Mplayer is different thing since it's command line player and it has a way to render video over window of different app.
Also it uses gstreamer to play media, there is already native/direct gstreamer support in subtitle composer.
Using xplayer to play media from sc would just another layer in between, so am not sure what would benefits be.

**Comment by muzena** [comment]
Xplayer is Mplayer 1. version
They fork gome apps because they have dependencies problem in every new version of Ubuntu so to avoid in every new version patching apps they fork them.  
Xplayer is mplayer 1. version, source code is the same as in mplayer 1. version. in source code they replace string mplayer with xplayer, so i think the api is the same, and it has also command options as mplayer.
 
I think that in subtitlecomposer configurations --> Waweform settings --> Text Fonts and colors --> Subtitle Number Color and Subtitle Text Color misiing colon.

And can you tell me which kde package must install to have icons in subtitlecomposer?

**Comment by maxrd2** [comment]
If XPlayer is fork of MPlayer and has identical commandline, you can just use MPlayer plugin and change exe path to /usr/bin/xplayer (or wherever it gets installed).
But by looking at the code it doesn't seem like it has anything to do with MPlayer to me.

Regarding icons... I suppose you need breeze-icons or some similarly named package.

**Comment by muzena** [comment]
Sorry, my mistake XPlayer is fork of Totem.
