### ISSUE TITLE
Opening videos from URL (e.g. on YouTube)

### ISSUE THREAD

**Issue by maxigaz** [maxrd2/SubtitleComposer#51]
Since I regularly make subtitles for a YouTube channel (not mine) and mpv can open those videos with the help of youtube-dl, I think it would be great if opening videos from a URL could be possible in Subtitle Composer.

And it would be even better if recently used URLs like these could also be accessed from the "Video" menu either among recently used local media or in a separate submenu.

**Comment by Martchus** [comment]
I think seeking would be inaccurate and slow. Additionally, the Waveform couldn't be displayed when relying completely on MPV for that feature because Subtitle Composer uses GStreamer to display the Waveform. Just downloading the video is not a big deal (you're using youtube-dl anyways).

Hence I believe implementing this feature isn't worth it.

**Comment by maxrd2** [comment]
It might be slow that's true, but might be cool feature. Current GStreamer implementation should be able to play video from http directly too.
Since waveform decoder is separate from video player it would download stream twice if played directly from http. Guess that could be solved by buffering in some temp file or by executing youtube-dl --dump-json URL which outputs variety of streams.. some are audio only, so some lowest quality audio-only stream could be used to generate waveform as fast as possible, and then save waveform data in ~/.cache/subtitlecomposer, and play video directly from stream that user selects (which should be fine with no changes in gstreamer/mplayer/mpv backend am not sure about xine/phonon).
Recent menu is no problem, will try doing some test of this in separate branch to see how it would work when i get some time.

**Comment by maxrd2** [comment]
Issue moved here: https://invent.kde.org/kde/subtitlecomposer/issues/11
