### ISSUE TITLE
Joining KDE

### ISSUE THREAD

**Issue by ghost** [maxrd2/SubtitleComposer#74]
Hi, I like this app very much and I'd like to see this project under KDE umbrella.
Is this possible? You can learn more about joining KDE here https://community.kde.org/Incubator
I'm not a developer, just a user. but I want to know your opinion.

**Comment by maxrd2** [comment]
I'd also like to see it as part of KDE at some point, glad to know there is more interest :)
The main problem right now I can think of is amount of time I can dedicate to the project.

**Comment by yambadr** [comment]
Well, you should give a try :)

**Comment by ognarb** [comment]
Hello KDE dev here :)

I discovered this project today, because it was posted in https://phabricator.kde.org/T10034.

We have a list of some advantages in joining KDE in https://manifesto.kde.org/benefits.html.

Joining KDE won't magically bring tons of new developers, but being part of it could help with marketing (post in planet.kde.org and dot.kde.org, weekly blog post from Nate, website, KDE brand), design (we have a VDG group where you ask for help concerning UX and UI), translations (there is a big community of translators in KDE), infrastructures (self hosted gitlab, mailing list, irc/matrix channel, build system) and more.

And for SubtitleComposer this would also mean a greater collaboration with other FOSS creative softwares (Krita and Kdenlive). Making the Kreative Suite ;)

Btw the content of https://community.kde.org/Incubator was greatly improved since 2017. If you have any question feel free to ask me or in the kde-devel mailing list.

**Comment by maxrd2** [comment]
@ognarb Hello there kde dev :)

Have already tried in the past (~4yrs ago i think) finding a sponsor for the project as I wanted to join KDE, Have asked on IRC and sent an email to kde-devel@kde.org where I was told to send it to some other mailing list where I might find someone willing to sponsor it.

So how do I go about finding a sponsor? Should I join discussion on https://phabricator.kde.org/T10034 ? Have already an account there, as I've already contributed in the past.

**Comment by ognarb** [comment]
I would recommend writing a new mail in kde-devel@kde.org asking for a sponsor for your project (I would recommend pointing out that this was proposed in https://phabricator.kde.org/T10034).

I'm currently doing web development, infra and promo stuff for KDE, so I may not be the best sponsor ;) But if nobody else is interested in being a sponsor, I would gladly be your sponsor.

**Comment by maxrd2** [comment]
Mail sent https://www.mail-archive.com/kde-devel@kde.org/msg11178.html

**Comment by maxrd2** [comment]
Project development has moved here: https://invent.kde.org/kde/subtitlecomposer

:)
